import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import MainSidebar from "@/components/MainSidebar";
import TopBar from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-[#F6F7FA]">
          <MainSidebar />
          <div className="flex flex-col w-full h-screen overflow-auto">
            <TopBar />
            <div className="p-8 flex-grow">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
