export const appointments = [
    {
        patientName: "Lindsay Walton",
        appointmentDate: "2024-09-03",
        appointmentTime: "10:00 AM",
        patientContact: "9827131123",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient experiencing mild headaches.",
    },
    {
        patientName: "Evan Peters",
        appointmentDate: "2024-09-03",
        appointmentTime: "11:00 AM",
        patientContact: "9827132143",
        appointmentType: "Follow-up",
        status: "Scheduled",
        doctorNotes: "Patient's blood pressure needs monitoring.",
    },
    {
        patientName: "Mia Rodriguez",
        appointmentDate: "2024-09-03",
        appointmentTime: "12:00 PM",
        patientContact: "9827133153",
        appointmentType: "Consultation",
        status: "Rescheduled",
        doctorNotes: "Patient is complaining of joint pain.",
    },
    {
        patientName: "Oliver Smith",
        appointmentDate: "2024-09-03",
        appointmentTime: "01:00 PM",
        patientContact: "9827134163",
        appointmentType: "Consultation",
        status: "Completed",
        doctorNotes: "Prescribed medication for allergies.",
    },
    {
        patientName: "Sophia Johnson",
        appointmentDate: "2024-09-03",
        appointmentTime: "02:00 PM",
        patientContact: "9827135173",
        appointmentType: "Check-up",
        status: "Scheduled",
        doctorNotes: "Routine check-up.",
    },
    {
        patientName: "Jackson Lee",
        appointmentDate: "2024-09-03",
        appointmentTime: "03:00 PM",
        patientContact: "9827136183",
        appointmentType: "Consultation",
        status: "Cancelled",
        doctorNotes: "Patient canceled the appointment.",
    },
    {
        patientName: "Ava Brown",
        appointmentDate: "2024-09-03",
        appointmentTime: "04:00 PM",
        patientContact: "9827137193",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient reports chest pain.",
    },
    {
        patientName: "Liam Wilson",
        appointmentDate: "2024-09-03",
        appointmentTime: "05:00 PM",
        patientContact: "9827138203",
        appointmentType: "Check-up",
        status: "Completed",
        doctorNotes: "Routine check-up, no issues reported.",
    },
    {
        patientName: "Emily Davis",
        appointmentDate: "2024-09-03",
        appointmentTime: "06:00 PM",
        patientContact: "9827139213",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient experiencing back pain.",
    },
    {
        patientName: "Lucas Martin",
        appointmentDate: "2024-09-04",
        appointmentTime: "10:00 AM",
        patientContact: "9827140223",
        appointmentType: "Follow-up",
        status: "Scheduled",
        doctorNotes: "Patient's recovery from surgery.",
    },
    {
        patientName: "Ella Garcia",
        appointmentDate: "2024-09-04",
        appointmentTime: "11:00 AM",
        patientContact: "9827141233",
        appointmentType: "Consultation",
        status: "Rescheduled",
        doctorNotes: "Patient reports fatigue and dizziness.",
    },
    {
        patientName: "Henry Martinez",
        appointmentDate: "2024-09-04",
        appointmentTime: "12:00 PM",
        patientContact: "9827142243",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient has a persistent cough.",
    },
    {
        patientName: "Olivia Hernandez",
        appointmentDate: "2024-09-04",
        appointmentTime: "01:00 PM",
        patientContact: "9827143253",
        appointmentType: "Check-up",
        status: "Completed",
        doctorNotes: "Routine check-up, patient is in good health.",
    },
    {
        patientName: "Alexander White",
        appointmentDate: "2024-09-04",
        appointmentTime: "02:00 PM",
        patientContact: "9827144263",
        appointmentType: "Consultation",
        status: "Cancelled",
        doctorNotes: "Patient canceled due to personal reasons.",
    },
    {
        patientName: "Sophia Thompson",
        appointmentDate: "2024-09-04",
        appointmentTime: "03:00 PM",
        patientContact: "9827145273",
        appointmentType: "Follow-up",
        status: "Scheduled",
        doctorNotes: "Patient recovering from an injury.",
    },
    {
        patientName: "Benjamin Moore",
        appointmentDate: "2024-09-04",
        appointmentTime: "04:00 PM",
        patientContact: "9827146283",
        appointmentType: "Consultation",
        status: "Completed",
        doctorNotes: "Patient reports improvement in symptoms.",
    },
    {
        patientName: "Charlotte Taylor",
        appointmentDate: "2024-09-04",
        appointmentTime: "05:00 PM",
        patientContact: "9827147293",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient has a skin rash.",
    },
    {
        patientName: "Sebastian Lewis",
        appointmentDate: "2024-09-04",
        appointmentTime: "06:00 PM",
        patientContact: "9827148303",
        appointmentType: "Check-up",
        status: "Rescheduled",
        doctorNotes: "Routine check-up rescheduled by patient.",
    },
    {
        patientName: "Amelia Clark",
        appointmentDate: "2024-09-05",
        appointmentTime: "10:00 AM",
        patientContact: "9827149313",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient reports insomnia and anxiety.",
    },
    {
        patientName: "Matthew Young",
        appointmentDate: "2024-09-05",
        appointmentTime: "11:00 AM",
        patientContact: "9827150323",
        appointmentType: "Follow-up",
        status: "Completed",
        doctorNotes: "Follow-up on medication effectiveness.",
    },
];
