export const appointments = [
  {
    patientName: "Lindsay Walton",
    appointmentDate: "2024-09-03",
    appointmentTime: "10:00 AM",
    patientContact: "9827131123",
    appointmentType: "Consultation",
    status: "Scheduled",
    doctorNotes: "Patient experiencing mild headaches.",
  },
  {
    patientName: "Evan Peters",
    appointmentDate: "2024-09-03",
    appointmentTime: "11:00 AM",
    patientContact: "9827132143",
    appointmentType: "Follow-up",
    status: "Scheduled",
    doctorNotes: "Patient's blood pressure needs monitoring.",
  },
  {
    patientName: "Mia Rodriguez",
    appointmentDate: "2024-09-03",
    appointmentTime: "12:00 PM",
    patientContact: "9827133153",
    appointmentType: "Consultation",
    status: "Rescheduled",
    doctorNotes: "Patient is complaining of joint pain.",
  },
  {
    patientName: "Oliver Smith",
    appointmentDate: "2024-09-03",
    appointmentTime: "01:00 PM",
    patientContact: "9827134163",
    appointmentType: "Consultation",
    status: "Completed",
    doctorNotes: "Prescribed medication for allergies.",
  },
  {
    patientName: "Sophia Johnson",
    appointmentDate: "2024-09-03",
    appointmentTime: "02:00 PM",
    patientContact: "9827135173",
    appointmentType: "Check-up",
    status: "Scheduled",
    doctorNotes: "Routine check-up.",
  },
  {
    patientName: "Jackson Lee",
    appointmentDate: "2024-09-03",
    appointmentTime: "03:00 PM",
    patientContact: "9827136183",
    appointmentType: "Consultation",
    status: "Cancelled",
    doctorNotes: "Patient canceled the appointment.",
  },
  {
    patientName: "Ava Brown",
    appointmentDate: "2024-09-03",
    appointmentTime: "04:00 PM",
    patientContact: "9827137193",
    appointmentType: "Consultation",
    status: "Scheduled",
    doctorNotes: "Patient reports chest pain.",
  },
  {
    patientName: "Liam Wilson",
    appointmentDate: "2024-09-03",
    appointmentTime: "05:00 PM",
    patientContact: "9827138203",
    appointmentType: "Check-up",
    status: "Completed",
    doctorNotes: "Routine check-up, no issues reported.",
  },
  {
    patientName: "Emily Davis",
    appointmentDate: "2024-09-03",
    appointmentTime: "06:00 PM",
    patientContact: "9827139213",
    appointmentType: "Consultation",
    status: "Scheduled",
    doctorNotes: "Patient experiencing back pain.",
  },
  {
    patientName: "Lucas Martin",
    appointmentDate: "2024-09-04",
    appointmentTime: "10:00 AM",
    patientContact: "9827140223",
    appointmentType: "Follow-up",
    status: "Scheduled",
    doctorNotes: "Patient's recovery from surgery.",
  },
  {
    patientName: "Ella Garcia",
    appointmentDate: "2024-09-04",
    appointmentTime: "11:00 AM",
    patientContact: "9827141233",
    appointmentType: "Consultation",
    status: "Rescheduled",
    doctorNotes: "Patient reports fatigue and dizziness.",
  },
  {
    patientName: "Henry Martinez",
    appointmentDate: "2024-09-04",
    appointmentTime: "12:00 PM",
    patientContact: "9827142243",
    appointmentType: "Consultation",
    status: "Scheduled",
    doctorNotes: "Patient has a persistent cough.",
  },
  {
    patientName: "Olivia Hernandez",
    appointmentDate: "2024-09-04",
    appointmentTime: "01:00 PM",
    patientContact: "9827143253",
    appointmentType: "Check-up",
    status: "Completed",
    doctorNotes: "Routine check-up, patient is in good health.",
  },
  {
    patientName: "Alexander White",
    appointmentDate: "2024-09-04",
    appointmentTime: "02:00 PM",
    patientContact: "9827144263",
    appointmentType: "Consultation",
    status: "Cancelled",
    doctorNotes: "Patient canceled due to personal reasons.",
  },
  {
    patientName: "Sophia Thompson",
    appointmentDate: "2024-09-04",
    appointmentTime: "03:00 PM",
    patientContact: "9827145273",
    appointmentType: "Follow-up",
    status: "Scheduled",
    doctorNotes: "Patient recovering from an injury.",
  },
  {
    patientName: "Benjamin Moore",
    appointmentDate: "2024-09-04",
    appointmentTime: "04:00 PM",
    patientContact: "9827146283",
    appointmentType: "Consultation",
    status: "Completed",
    doctorNotes: "Patient reports improvement in symptoms.",
  },
  {
    patientName: "Charlotte Taylor",
    appointmentDate: "2024-09-04",
    appointmentTime: "05:00 PM",
    patientContact: "9827147293",
    appointmentType: "Consultation",
    status: "Scheduled",
    doctorNotes: "Patient has a skin rash.",
  },
  {
    patientName: "Sebastian Lewis",
    appointmentDate: "2024-09-04",
    appointmentTime: "06:00 PM",
    patientContact: "9827148303",
    appointmentType: "Check-up",
    status: "Rescheduled",
    doctorNotes: "Routine check-up rescheduled by patient.",
  },
  {
    patientName: "Amelia Clark",
    appointmentDate: "2024-09-05",
    appointmentTime: "10:00 AM",
    patientContact: "9827149313",
    appointmentType: "Consultation",
    status: "Scheduled",
    doctorNotes: "Patient reports insomnia and anxiety.",
  },
  {
    patientName: "Matthew Young",
    appointmentDate: "2024-09-05",
    appointmentTime: "11:00 AM",
    patientContact: "9827150323",
    appointmentType: "Follow-up",
    status: "Completed",
    doctorNotes: "Follow-up on medication effectiveness.",
  },
];

export const medicalHistory = [
  {
    date: "2023-08-15",
    condition: "Hypertension",
    diagnosis: "Essential Hypertension",
    doctor: "Dr. John Doe",
    status: "Ongoing",
    notes: "Patient advised to reduce salt intake and prescribed medication.",
  },
  {
    date: "2023-06-10",
    condition: "Diabetes Type 2",
    diagnosis: "Type 2 Diabetes Mellitus",
    doctor: "Dr. Emily Smith",
    status: "Ongoing",
    notes: "Patient prescribed Metformin and advised on diet control.",
  },
  {
    date: "2023-03-20",
    condition: "Asthma",
    diagnosis: "Chronic Asthma",
    doctor: "Dr. Michael Lee",
    status: "Controlled",
    notes: "Patient using inhaler regularly; no recent attacks.",
  },
  {
    date: "2023-01-12",
    condition: "Allergic Rhinitis",
    diagnosis: "Seasonal Allergic Rhinitis",
    doctor: "Dr. Sarah Williams",
    status: "Resolved",
    notes: "Patient responded well to antihistamines; symptoms resolved.",
  },
  {
    date: "2022-11-05",
    condition: "Migraine",
    diagnosis: "Chronic Migraine",
    doctor: "Dr. Robert Brown",
    status: "Ongoing",
    notes: "Patient prescribed triptans; advised to avoid triggers.",
  },
  {
    date: "2022-08-22",
    condition: "Gastritis",
    diagnosis: "Acute Gastritis",
    doctor: "Dr. Linda Taylor",
    status: "Resolved",
    notes:
      "Patient advised to avoid spicy foods; symptoms resolved after treatment.",
  },
  {
    date: "2022-05-30",
    condition: "Anemia",
    diagnosis: "Iron-Deficiency Anemia",
    doctor: "Dr. Kevin Anderson",
    status: "Resolved",
    notes: "Patient prescribed iron supplements; hemoglobin levels normalized.",
  },
  {
    date: "2022-03-14",
    condition: "High Cholesterol",
    diagnosis: "Hyperlipidemia",
    doctor: "Dr. Angela Martinez",
    status: "Ongoing",
    notes: "Patient advised on dietary changes; prescribed statins.",
  },
  {
    date: "2021-12-01",
    condition: "Depression",
    diagnosis: "Major Depressive Disorder",
    doctor: "Dr. David Clark",
    status: "Ongoing",
    notes: "Patient undergoing therapy and taking antidepressants.",
  },
  {
    date: "2021-09-18",
    condition: "Back Pain",
    diagnosis: "Mechanical Back Pain",
    doctor: "Dr. James Wilson",
    status: "Resolved",
    notes: "Patient recovered after physiotherapy sessions.",
  },
];

export const allergiesData = [
  {
    allergen: "Peanuts",
    reactionType: "Anaphylaxis",
    severity: "Severe",
    dateIdentified: "2022-03-15",
    notes: "Carry an EpiPen at all times.",
  },
  {
    allergen: "Shellfish",
    reactionType: "Hives",
    severity: "Moderate",
    dateIdentified: "2021-06-10",
    notes: "Avoid all types of shellfish.",
  },
  {
    allergen: "Penicillin",
    reactionType: "Rash",
    severity: "Mild",
    dateIdentified: "2020-12-01",
    notes: "Alternative antibiotics are required.",
  },
  {
    allergen: "Dust mites",
    reactionType: "Sneezing",
    severity: "Mild",
    dateIdentified: "2019-11-22",
    notes: "Use hypoallergenic bedding.",
  },
  {
    allergen: "Pollen",
    reactionType: "Watery Eyes",
    severity: "Mild",
    dateIdentified: "2018-04-05",
    notes: "Take antihistamines during spring.",
  },
  {
    allergen: "Latex",
    reactionType: "Skin Irritation",
    severity: "Moderate",
    dateIdentified: "2017-09-12",
    notes: "Avoid latex gloves and products.",
  },
  {
    allergen: "Cat dander",
    reactionType: "Asthma",
    severity: "Severe",
    dateIdentified: "2016-02-17",
    notes: "Keep away from cats and use inhaler as needed.",
  },
  {
    allergen: "Milk",
    reactionType: "Eczema",
    severity: "Moderate",
    dateIdentified: "2015-08-30",
    notes: "Avoid all dairy products.",
  },
  {
    allergen: "Bees",
    reactionType: "Swelling",
    severity: "Severe",
    dateIdentified: "2014-07-14",
    notes: "Seek immediate medical attention if stung.",
  },
  {
    allergen: "Wheat",
    reactionType: "Digestive Issues",
    severity: "Moderate",
    dateIdentified: "2013-10-21",
    notes: "Follow a gluten-free diet.",
  },
];

export const pastSurgeries = [
  {
    date: "2021-05-12",
    name: "Appendectomy",
    surgeon: "Dr. Rajesh Kumar",
    hospital: "Apollo Hospital",
    outcome: "Successful",
    notes: "No complications, routine follow-up advised.",
  },
  {
    date: "2019-11-30",
    name: "Knee Replacement",
    surgeon: "Dr. Anjali Mehta",
    hospital: "Fortis Hospital",
    outcome: "Successful",
    notes: "Physical therapy required for 6 months post-surgery.",
  },
  {
    date: "2020-08-22",
    name: "Gallbladder Removal",
    surgeon: "Dr. Suresh Bansal",
    hospital: "AIIMS",
    outcome: "Successful",
    notes: "Diet modification recommended.",
  },
  {
    date: "2018-02-14",
    name: "Cataract Surgery",
    surgeon: "Dr. Pooja Sharma",
    hospital: "Max Healthcare",
    outcome: "Successful",
    notes: "Vision improved significantly.",
  },
  {
    date: "2017-06-10",
    name: "Hip Replacement",
    surgeon: "Dr. Anil Singh",
    hospital: "Medanta",
    outcome: "Complications",
    notes: "Post-op infection managed with antibiotics.",
  },
  {
    date: "2019-03-25",
    name: "Hernia Repair",
    surgeon: "Dr. Nitin Gupta",
    hospital: "Columbia Asia Hospital",
    outcome: "Successful",
    notes: "Discharged on the same day.",
  },
  {
    date: "2022-01-10",
    name: "Coronary Artery Bypass Grafting",
    surgeon: "Dr. Sunil Verma",
    hospital: "Narayana Health",
    outcome: "Successful",
    notes: "Regular cardiac check-ups advised.",
  },
  {
    date: "2016-09-15",
    name: "Tonsillectomy",
    surgeon: "Dr. Priya Das",
    hospital: "Manipal Hospital",
    outcome: "Successful",
    notes: "Slight throat irritation post-surgery.",
  },
  {
    date: "2023-03-05",
    name: "Thyroidectomy",
    surgeon: "Dr. Ravi Patel",
    hospital: "Fortis Hospital",
    outcome: "Successful",
    notes: "Hormone replacement therapy started.",
  },
  {
    date: "2020-07-19",
    name: "Spinal Fusion",
    surgeon: "Dr. Sameer Malhotra",
    hospital: "Artemis Hospital",
    outcome: "Successful",
    notes: "Regular physiotherapy sessions required.",
  },
];
